package com.filpatterson.demo.services;

import org.springframework.stereotype.Component;

import com.filpatterson.demo.interfaces.FortuneService;

//	here if name of class would be "RESTFortuneService", then autogenerated name of bean
// would be "RESTFortuneService", because Spring doesn't convert names of beans, where
// sequentially are placed two upper case characters
@Component
public class RestFortuneService implements FortuneService {

	@Override
	public String getFortune() {
		return "here is rest service fortune!";
	}

}
